# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  servo1:
    min_position: 0
    max_position: 5.23598
    has_velocity_limits: true
    max_velocity: 11.938
    has_acceleration_limits: false
    max_acceleration: 0
  servo2:
    min_position: 0
    max_position: 5.23598
    has_velocity_limits: true
    max_velocity: 11.938
    has_acceleration_limits: false
    max_acceleration: 0
  servo3:
    min_position: 0
    max_position: 5.23598
    has_velocity_limits: true
    max_velocity: 11.938
    has_acceleration_limits: false
    max_acceleration: 0
  servo4:
    min_position: 0
    max_position: 5.23598
    has_velocity_limits: true
    max_velocity: 11.938
    has_acceleration_limits: false
    max_acceleration: 0
